import MainScreen, {
  Home,
  Search,
  Settings,
  Login,
  Register,
  ForgotPassword,
  Otp,
  ResetPassword,
  Restaurant,
  CreateAddress,
  AddressManager,
  Detail,
  OrderDetail,
  OrderManagement,
  OrderConfirm,
  OrderStatus,
} from './screens';
import SearchCategory from './screens/food/SearchCategory';

export {
  Home,
  Search,
  Settings,
  MainScreen,
  Login,
  Register,
  ForgotPassword,
  Otp,
  ResetPassword,
  Detail,
  OrderManagement,
  OrderDetail,
  OrderStatus,
  Restaurant,
  OrderConfirm,
  SearchCategory,
  AddressManager,
  CreateAddress,
};
